alias: OMIPS-2018-Centro

admin-groups: [OMI-2018]

tags: [omips2018]

generate-output: true
solution: solutions/100A.kp
timeout: 2

params:
  title: Centro del Rect√°ngulo
  source: OMIPS 2018 (Alexis Cervantes)

  visibility: 1

  languages: karel

  time_limit: 1000
  memory_limit: 32768
  output_limit: 16384
  stack_limit: 10485760

  overall_wall_time_limit: 60000

  validator: token-caseless
  validator_time_limit: 1000
  extra_wall_time: 0

  email_clarifications: 0
